class Univ < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '札幌大学', prefecture_id: 1 },
    { id: 2, name: '青森大学', prefecture_id: 2  },
    { id: 3, name: '岩手医科大学', prefecture_id: 3  },
    { id: 4, name: '盛岡大学', prefecture_id: 4  },
    { id: 5, name: '秋田看護福祉大学', prefecture_id: 5  }, 
    { id: 6, name: '山形大学', prefecture_id: 6  },
    { id: 7, name: '福島大学', prefecture_id: 7  }, 
    { id: 8, name: '茨城大学', prefecture_id: 8  }, 
    { id: 9, name: '栃木大学', prefecture_id: 9  },
    { id: 10, name: '群馬大学', prefecture_id: 10  }, 
    { id: 11, name: '埼玉大学', prefecture_id: 11  }, 
    { id: 12, name: '千葉大学', prefecture_id: 12  },
    { id: 13, name: '東京大学', prefecture_id: 13  }, 
    { id: 14, name: '慶應義塾大学', prefecture_id: 13  }, 
    { id: 15, name: '東京医科大学', prefecture_id: 13  }, 
    { id: 16, name: '神奈川大学', prefecture_id: 14  }, 
    { id: 17, name: '新潟大学', prefecture_id: 15  },
    { id: 18, name: '富山大学', prefecture_id: 16  }, 
    { id: 19, name: '石川大学', prefecture_id: 17  }, 
    { id: 20, name: '福井大学', prefecture_id: 18  },
    { id: 21, name: '山梨大学', prefecture_id: 19  }, 
    { id: 22, name: '長野大学', prefecture_id: 20  }, 
    { id: 23, name: '岐阜大学', prefecture_id: 21  },
    { id: 24, name: '静岡大学', prefecture_id: 22 }, 
    { id: 25, name: '愛知大学', prefecture_id: 23  }, 
    { id: 26, name: '三重大学', prefecture_id: 24  },
    { id: 27, name: '滋賀大学', prefecture_id: 25  }, 
    { id: 28, name: '京都大学', prefecture_id: 26  }, 
    { id: 29, name: '京都女子大学', prefecture_id: 26  }, 
    { id: 30, name: '立命館大学', prefecture_id: 26  }, 
    { id: 31, name: '龍谷大学', prefecture_id: 26  }, 
    { id: 32, name: '大阪大学', prefecture_id: 27  },
    { id: 33, name: '兵庫大学', prefecture_id: 28  }, 
    { id: 34, name: '奈良大学', prefecture_id: 29  }, 
    { id: 35, name: '和歌山大学', prefecture_id: 30  },
    { id: 36, name: '鳥取大学', prefecture_id: 31  }, 
    { id: 37, name: '島根大学', prefecture_id: 32  }, 
    { id: 38, name: '岡山大学', prefecture_id: 33  },
    { id: 39, name: '広島大学', prefecture_id: 34  }, 
    { id: 40, name: '山口大学', prefecture_id: 35  }, 
    { id: 41, name: '徳島大学', prefecture_id: 36  },
    { id: 42, name: '香川大学', prefecture_id: 37  }, 
    { id: 43, name: '愛媛大学', prefecture_id: 38  }, 
    { id: 44, name: '高知大学', prefecture_id: 39  },
    { id: 45, name: '福岡大学', prefecture_id: 40  }, 
    { id: 46, name: '佐賀大学', prefecture_id: 41  }, 
    { id: 47, name: '長崎大学', prefecture_id: 42  },
    { id: 48, name: '熊本大学', prefecture_id: 43  }, 
    { id: 49, name: '大分大学', prefecture_id: 44  }, 
    { id: 50, name: '宮崎大学', prefecture_id: 45  },
    { id: 51, name: '鹿児島大学', prefecture_id: 46  }, 
    { id: 52, name: '琉球大学', prefecture_id: 47  }
  ]

  # belongs_to :prefecture
end